version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bitcoin-core

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: testdb

  bitcoin-core:
    image: ruimarinho/bitcoin-core
    command:
      -printtoconsole
      -regtest=1