services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NETWORK: regtest
      ADDRESS: bitcoin-core:18444
    depends_on:
      - bitcoin-core

  bitcoin-core:
    image: ruimarinho/bitcoin-core
    command:
      -printtoconsole
      -regtest=1
    ports:
      - 18444:18444
